### ISSUE TITLE
March 2019 Update 

### ISSUE THREAD

**Issue by Feary** [Caradog/XI-View#10]
Seems it was broken from forum posts. i know that it was removed from my days with update. i haven't tried to replace with current files here because of whats been said.

**Comment by Caradog** [comment]
I'll take a look at it, chances are they just added more icons - won't have a chance to look at it till the weekend though

**Comment by Feary** [comment]
cool thanks

**Comment by Caradog** [comment]
Taken a look, it looks like SE updated an icon description, going to forgo updating at this time - if any further issues are noticed please advise
