### ISSUE TITLE
May 2019 Version Update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#11]
SE said that they are redesigning the Config menu. There will probably need to be heavy editing. Update scheduled for May 10th.

**Comment by Caradog** [comment]
The download doesn't seem to have affected my files, looking like no major changes that require a rework, will leave this open for a week for people to report issues if any arise

**Comment by palladin9479** [comment]
They added some icons and it seems to break for some people if they aren't present.
https://www.ffxiah.com/forum/topic/44787/jeanpauls-dat-mod-workshop/6/#3430851

**Comment by Caradog** [comment]
My apologies, I should of looked more closely - will release a fix by tomorrow morning

**Comment by Caradog** [comment]
I've just pushed an update that should hopefully fix the icon issue, I've given the new sacrifice buff the icon used when you caress a debuff, I've used the exp+ icon for the pot buff

As usual if there's any issues at all please feel free to let me know

**Comment by palladin9479** [comment]
Thanks man!
