### ISSUE TITLE
June 2019 Update

### ISSUE THREAD

**Issue by KazyEXE** [Caradog/XI-View#12]
They added a new icon, Emporox's Gift, that gets overwritten when using these.

Looks like this person has it fixed:
https://github.com/KenshiDRK/XiView

**Comment by Caradog** [comment]
Apologies for the slow response, will fix this when the next update hits

**Comment by KazyEXE** [comment]
New update's out, seems to have reset again but I'm not sure if there's any new icons

**Comment by funkworkz** [comment]
They modified the Emporox Gift icon's size is all. Update would still be nice though.

**Comment by Caradog** [comment]
Pushed an update - any issues lemme know

Edit: Will close this in a few days if no issues
