### ISSUE TITLE
Spirit Bond buff icon

### ISSUE THREAD

**Issue by MartelRagnarok** [Caradog/XI-View#14]
The buff icon for the new spirit bond icon is the debug/BC icon in the latest version of XI-View.

**Comment by Caradog** [comment]
I just tested this myself on Dragoon and am getting the correct buff I reused for Spirit Bond - are you sure you have 2.0.10 installed?

![img_20191011_143435](https://user-images.githubusercontent.com/6230002/66655811-ac9dfb80-ec34-11e9-9d7f-c800f66b7751.png)

**Comment by MartelRagnarok** [comment]
Huh. I had thought I'd downloaded the latest version. But perhaps mistakes were made on my part.  I'll re-download and re-install  when I get home to confirm.

**Comment by MartelRagnarok** [comment]
Silly question but.. how do you confirm which version you're downloading? I downloaded from the Clone or download button on https://github.com/Caradog/XI-View. But I don't see any indication of which version I'm getting.

**Comment by Caradog** [comment]
Typically you always get the latest version from Github, the only way to get the repo at an older state is to click through the commit history: https://github.com/Caradog/XI-View/commits/master

If you click the <>s you view (and can download) the repo in its state at that commit

**Comment by MartelRagnarok** [comment]
Well, I figured it out. I did this to myself. Months ago, I setup XIpivot, that addon that handles active dat swaps, rather than replacing your original files. And I included the XIview icons as part of this...

Then completely for got about it. In short, XIview is fine and I'm an idiot. /facepalm. Thank you for your patience.

**Comment by Caradog** [comment]
No problem at all, I wasn't aware of XIpivot so thank you for bringing that to my attention
