### ISSUE TITLE
Not an Issue, QoL question of songs distinguish.

### ISSUE THREAD

**Issue by Wotasu** [Caradog/XI-View#16]
Love the xi-view! But is it possible to make the bard songs more specific, for example to see which is Honor March or Victory March, or Minuet 3-5.

**Comment by Caradog** [comment]
Unfortunately not possible as all songs of the same type call the same icon

**Comment by Wotasu** [comment]
Ok, thank you for your response. I figured there was something like that or it would have been added long ago. But I wanted to ask!



________________________________
