### ISSUE TITLE
Changing fonts for menus

### ISSUE THREAD

**Issue by Zirk40** [Caradog/XI-View#19]
Not a real issue. I like the modified 119/51.DAT except I want to keep the default fonts. The how to swap fonts pdf explains changing "font font" but this doesn't change the fonts in the top right corner menu and some other menus. Is there a default DDS provided in this repository which can replace the menu fonts, and if so which item in 119/51.DAT needs to change?

**Comment by Caradog** [comment]
There's 3 different dds images in XI View responsible for changing the font: font font, font moji & menu menu2fon

From the sounds of it, you're looking to change menu2fon (as moji handles the chat box I believe), looking through Deathbringer's fonts it looks like there's only dds images available for font font unfortunately

**Comment by Zirk40** [comment]
Yes I tried changing menu menu2fon with the provided DDS since they were both 256x256, but it garbled things. The stuff that was garbled was the chat box label i.e. "Window1:Say" and other small texts around the UI. Thanks for the info and fast response!
