### ISSUE TITLE
XIview issues after latest game update

### ISSUE THREAD

**Issue by Wotasu** [Caradog/XI-View#21]
Seems to be an issue with the old xiview version and the new chat function.
And backup files arent working either cause updates c.c
Game total crash when I expand the chat log
Managed to find the updated ffxi original dats from a friend and game isnt crashing anymore when I expand chat log.

**Comment by Caradog** [comment]
Figured the Assist stuff might cause issues, will fix it later today

**Comment by PenanceXI** [comment]
Can confirm. Just wanted to say thank you @Caradog for your work.

**Comment by kuroganashi** [comment]
Thanks Dogg

**Comment by FuzzTech** [comment]
you're amazing thanks !

**Comment by Kingfisher1980** [comment]
Is there any sort of temporary fix available for now to get by until the actual issue is fixed up?

**Comment by PenanceXI** [comment]
> Is there any sort of temporary fix available for now to get by until the actual issue is fixed up?

Launch PlayOnline, choose Check Files (or something similar), when it opens up, click the dropdown box and select FFXI instead of PlayOnline and let it repair the games files. This will stop the crashing problem but also remove any .DAT modifications you may have made in the past. The process will take roughly 20-30 minutes.

I believe that other mods such as XI Vision are having the same crashing issue when expanding the chat log.

**Comment by Kingfisher1980** [comment]
> > Is there any sort of temporary fix available for now to get by until the actual issue is fixed up?
> 
> Launch PlayOnline, choose Check Files (or something similar), when it opens up, click the dropdown box and select FFXI instead of PlayOnline and let it repair the games files. This will stop the crashing problem but also remove any .DAT modifications you may have made in the past. The process will take roughly 20-30 minutes.
> 
> I believe that other mods such as XI Vision are having the same crashing issue when expanding the chat log.

Yea I use XiPivot in Ashita so I just disabled the XIViewer for now. :/ Bummed because I just set it up and last night and was loving the new menus and icons... I guess its bubble menus until a better fix is found.

**Comment by Caradog** [comment]
I've pushed an update that should correct the issue, will leave this open for a few days in case any further issues appear related to the Oct 2020 update.
