### ISSUE TITLE
October 2029 icon debug mode

### ISSUE THREAD

**Issue by Miltani** [Caradog/XI-View#22]
There seemed to be some changes to some of the status icon numbering. Icon for potpourri became debug options icon.

**Comment by Caradog** [comment]
I've just logged in and can't seem to replicate this - as far as I can tell the file with status icons wasn't changed. Would you be able to advise if you're using widescreen/normal and the language of your client?

**Comment by Miltani** [comment]
I am using the wide screen and my client is us
Is this information enough? I can add an image later if needed

**Comment by Miltani** [comment]
Seemed like the icon resolved itself when windower did some resource update.

**Comment by Caradog** [comment]
Would you be using XIpivot (think that's the name)?
