### ISSUE TITLE
Crash after November 2020 Update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#24]
After completing the new mentor roe, enabling the mentor status, and then viewing the Status > Profile window, the game crashes.

**Comment by Caradog** [comment]
Yeah I figured this would cause a crash, I'll fix it as soon as I'm able but I won't get any time to look at it till the earliest of tomorrow

**Comment by ckendall11** [comment]
not sure if this is the best place to comment, but how would I go about helping out on these fixes for future patches and whatnot?

**Comment by Caradog** [comment]
> not sure if this is the best place to comment, but how would I go about helping out on these fixes for future patches and whatnot?


If you would like to contribute to the project, please feel free to create a fork and request a merger

**Comment by Caradog** [comment]
> After completing the new mentor roe, enabling the mentor status, and then viewing the Status > Profile window, the game crashes.

Should be fixed after the latest update push
