### ISSUE TITLE
Significant update tonight

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#29]
New menus, wardrobes, etc happening tonight. Most certainly will break the dats.

**Comment by Caradog** [comment]
Hi Funk - thanks, will take a look at the update as soon as I can

**Comment by Caradog** [comment]
Update pushed - will keep an eye out for issues

**Comment by funkworkz** [comment]
Thanks for getting this done so quick, if any issues occur I will post.

**Comment by zach51791** [comment]
~~With update for the new mogwardrobes, it doesn’t show the slots for new wardrobes it’ll only shows up to 4 and there 8 now :( any chance you can update this?~~

Removing this since it isn't related to the original issue and it has been replicated in another thread.

**Comment by Caradog** [comment]
Closing as no issues have been reported with the update.
