### ISSUE TITLE
Mog wardrobes

### ISSUE THREAD

**Issue by zach51791** [Caradog/XI-View#30]
Can you add the new mog wardrobes in its only shows up to 4 and no way to Access the new ones. Love this mod thanks so much!!!

**Comment by Caradog** [comment]
![image](https://user-images.githubusercontent.com/6230002/165794366-86b0419d-ab89-41a5-96b4-ff2801794c16.png)

I think you're likely using an out-dated version of XI View - the above screenshot is from my own client.

**Comment by zach51791** [comment]
Oh my I will look into this thanks so much!

**Comment by zach51791** [comment]
I go to code and download ya? :) thanks for the help btw I might be unsure where updated one is or how to access sorry for the trouble!

**Comment by zach51791** [comment]
![Uploading image.jpg…]()

**Comment by zach51791** [comment]
I got it figured it out! You guys are amazing ffxi really will always be home and you allowed players to relive ffxi in a new way thanks for all your hard work!!!!
