### ISSUE TITLE
Suggestion: Honor March Icon

### ISSUE THREAD

**Issue by Shylo-Musgrove** [Caradog/XI-View#31]
I have ran into many instances when someone loses a march (dispel) but we are not able to identify which one. Is it possible to make the Honor March icon stand out from the other March icons? Maybe use two _8th notes with a stem_ or give it its own color entirely?

Just a thought. Love XI-View!

**Comment by Caradog** [comment]
All the songs of the same type share a icon, unfortunately it is not possible to separate them out to differentiate them.

Thanks for the support.
