### ISSUE TITLE
September 2022 Update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#32]
Update overwrote XIView files. Unsure if there are changes, nothing is in the notes about icons.

**Comment by Caradog** [comment]
Thanks for opening an issue.
I'm currently looking at this - I can't see any changes to the icons so I'm not sure why they were overwritten.
I can't check the UI file as easily, as there's a large chunk I don't interact with and no easy way to compare.
Currently I'm using the old version - will leave this issue open in case anything comes up.

**Comment by oakiedoak** [comment]
Yep, not working for me either. I have XI-View set to auto load with XIPivot and its not working anymore. Re-downloaded the latest XI-View and overwrote the existing files in XIPivot as well. Not loading up for some reason.

**Comment by Caradog** [comment]
> Yep, not working for me either. I have XI-View set to auto load with XIPivot and its not working anymore. Re-downloaded the latest XI-View and overwrote the existing files in XIPivot as well. Not loading up for some reason..

XI Pivot has never worked correctly with XI View, please install it directly into the dats and disable XI Pivot to see if the issue persists

**Comment by oakiedoak** [comment]
> > Yep, not working for me either. I have XI-View set to auto load with XIPivot and its not working anymore. Re-downloaded the latest XI-View and overwrote the existing files in XIPivot as well. Not loading up for some reason..
> 
> XI Pivot has never worked correctly with XI View, please install it directly into the dats and disable XI Pivot to see if the issue persists

Thanks! This worked for me. Didn't realize XIPivot did not work for this.

**Comment by Caradog** [comment]
Going to close this issue - looks like the files after the update are identical - not sure why they were overwritten.
