### ISSUE TITLE
May 2023 Update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#35]
A new icon was added for upcoming Prime Weapon aftermath and/or/maybe not afterglow.

**Comment by Caradog** [comment]
As there's second update this month and the changes don't affect compatibility (nor do I think the status icons are currently accessible), I'll be updating this after the subsequent update to rule out further required changes

**Comment by Caradog** [comment]
I've just pushed an update, should resolve the above issue. Will leave this open for a few days in case any new issues crop up.
