### ISSUE TITLE
SE made changes to menus

### ISSUE THREAD

**Issue by RickBoogs** [Caradog/XI-View#39]
Just fyi, SE made changes to the Quests menu section this update. May need adjustments if possible.^^

**Comment by RickBoogs** [comment]
Thanks for keeping this updated btw! Hope I didn't rush you.

**Comment by Caradog** [comment]
Thanks for letting me know - and for the kind words
Update should have fixed this issue - will leave this open for a few days in case of other issues

**Comment by RickBoogs** [comment]
It works great! Thanks again. This pack is my favorite!
