### ISSUE TITLE
.DAT changes

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#4]
Both of the files below were changed this month:

ROM/0/12.DAT and
ROM/119/57.DAT

PS: Should I keep making an issue post when changes happen? Is it useful or just an annoyance?

**Comment by Caradog** [comment]
Just pushed an update

**Comment by funkworkz** [comment]
Wow that was quick, thanks a lot!

PS: Should I keep making an issue post when changes happen? Is it useful or just an annoyance?

**Comment by Caradog** [comment]
Idm, I'm still active atm so I should see changes, it emails me though so its a nice reminder to keep it up to date here too
