### ISSUE TITLE
Jun Update

### ISSUE THREAD

**Issue by Kingfisher1980** [Caradog/XI-View#40]
Unsure if this is a result of this, or another pack I have running in Pivot, but the game loads fine, menus seem to be fine, but as soon as I open the equip screen... BEWM Crash! I assume this has something to do with the icon change related to cansendpol? If this is not related please let me know so I can try and figure out what I need to fix!

**Comment by Caradog** [comment]
It looks like the UI dat was changed, I'll figure out an update as soon as I'm able - likely by tomorrow.
Thanks for letting me know

**Comment by RickBoogs** [comment]
Thanks again Caradog for keeping this updated for us!

**Comment by palladin9479** [comment]
Any word on the update?  Currently it crash's FFXI when applied.

**Comment by Caradog** [comment]
Just pushed an update that should fix it.
Will leave this open in case further issues arise - if they do report here please

**Comment by palladin9479** [comment]
Thanks a million!
