### ISSUE TITLE
fonts

### ISSUE THREAD

**Issue by Noctis32** [Caradog/XI-View#6]
Hi there, I was wondering what is the default font use in ffxi view? I recently upgraded to 4k and the fonts look a lil blurry so I was thinking of attempting to upgrade the fonts textures from 256x256 to 512x512.

**Comment by Caradog** [comment]
Which font are you referring to? The font above the models used for names or the chat log font?

**Comment by Noctis32** [comment]
The fonts for the chat log and also for names above the characters.

**Comment by Caradog** [comment]
The dds files are contained in 119/51 and are named Font Moji and Font Font, I'm not sure changetex would allow anything other than a dds with the correct resolution to be entered, perhaps with hex editing, I've uploaded the dds image files here: https://www.dropbox.com/sh/vyb2fhtjklk9szb/AADn_SUa6QxWZad_-7DFvtDPa?dl=0
