### ISSUE TITLE
May 2018 Update

### ISSUE THREAD

**Issue by funkworkz** [Caradog/XI-View#7]
New song icons were added, and they suck. Is the current XIView version compatible with the newest update?

**Comment by Sechs** [comment]
Using the previous 57.dat (and just that) generated an invisible icon on Chocobo Mazurka and made me crash on Hymnus.
Tried three times, same result all of them, had to resort going back to the original 57.dat.

Caradogg do something please good sir!

**Comment by Caradog** [comment]
Taking a look at the file, I'm surprised it caused a crash but yeah I can see they've only altered the song files

I'll release an updated version either tonight when I return home for work or tomorrow morning

**Comment by Sechs** [comment]
Yeah! Thanks Caradog, can't wait for your special update to be released ^^

**Comment by Caradog** [comment]
I've released an updated version on a separate branch, if I don't get any complaints of crashes etc I'll merge them in a few days

**Comment by lewyo** [comment]
Thanks for the update Caradog^^ and hopefully no news means good news ^^
